openapi: 3.0.0
components:
  schemas:
    ProductItem:
      type: object
      properties:
        id:
          type: string
          description: The unique product id
        count:
          type: number
          description: Product quantity
        description:
          type: string
          description: Product description
        price:
          type: number
          description: Product item price
        title:
          type: string
          description: Product name
    ProductItemsArray:
      title: Product Items Schema
      description: >-
        This is a schema for responses in the JSON API format. For more, see
        http://jsonapi.org
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductItem'
      additionalProperties: false
      default:
        $schema: 'http://json-schema.org/draft-04/schema#'
        title: Product Items Schema
        description: >-
          This is a schema for responses in the JSON API format. For more, see
          http://jsonapi.org
        type: object
        properties:
          products:
            type: array
            items:
              $ref: '#/components/schemas/ProductItem'
        definitions:
          ProductItem:
            type: object
            properties:
              id:
                type: string
                description: The unique product id
              count:
                type: number
                description: Product quantity
              description:
                type: string
                description: Product description
              price:
                type: number
                description: Product item price
              title:
                type: string
                description: Product name
        additionalProperties: false
info:
  title: Product Service API
  description: Simple API to get products
  version: 1.0.0
paths:
  /products:
    get:
      operationId: getProductsList
      summary: Get all available products
      description: Get all available products
      parameters: []
      responses:
        '200':
          description: All available products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductItemsArray'
        '500':
          description: An error message when getting all products
          content: {}
  '/products/{productId}':
    get:
      operationId: getProductById
      summary: Get product by id
      description: Returns single product by it's id
      parameters:
        - name: id
          in: path
          description: The unique product id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An object with the found product data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductItem'
        '404':
          description: Product with such id not found
          content: {}
        '500':
          description: An error message when getting a product
          content: {}
